_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "TargetedAttackedGeneralizedRCNN"
  BACKBONE:
    NAME: "build_vgg_backbone"
  PROPOSAL_GENERATOR:
    NAME: "BgPseudoRPN"
  RPN:
    IN_FEATURES: ["vgg_block5"]
  ROI_HEADS:
    NAME: "FgPseudoROIHeads"
    NUM_CLASSES: 8
    IN_FEATURES: ["vgg_block5"]
SOLVER:
  STEPS: (30000,)
  MAX_ITER: 30000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.016
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2000
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("cityscapes_train",)
  TRAIN_UNLABEL: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
SEMISUPNET:
  Trainer: "tateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 4000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "vgg_block5" #["concate","p2","multi"]
TEST:
  EVAL_PERIOD: 500